[package]
name = "manifestation"
version = "0.2.0"
authors = ["Ash <ashe.null@protonmail.ch>"]
edition = "2018"

[dependencies]
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[profile.release]
lto = true